// Code generated by MockGen. DO NOT EDIT.
// Source: ./interface.go
//
// Generated by this command:
//
//	mockgen -package key -mock_names IHandlers=HandlersMock -source ./interface.go -typed -destination interface.mock.gen.go
//

// Package key is a generated GoMock package.
package key

import (
	reflect "reflect"

	fiber "github.com/gofiber/fiber/v2"
	gomock "go.uber.org/mock/gomock"
)

// HandlersMock is a mock of IHandlers interface.
type HandlersMock struct {
	ctrl     *gomock.Controller
	recorder *HandlersMockMockRecorder
	isgomock struct{}
}

// HandlersMockMockRecorder is the mock recorder for HandlersMock.
type HandlersMockMockRecorder struct {
	mock *HandlersMock
}

// NewHandlersMock creates a new mock instance.
func NewHandlersMock(ctrl *gomock.Controller) *HandlersMock {
	mock := &HandlersMock{ctrl: ctrl}
	mock.recorder = &HandlersMockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *HandlersMock) EXPECT() *HandlersMockMockRecorder {
	return m.recorder
}

// InsertPage mocks base method.
func (m *HandlersMock) InsertPage(c *fiber.Ctx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertPage", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertPage indicates an expected call of InsertPage.
func (mr *HandlersMockMockRecorder) InsertPage(c any) *HandlersMockInsertPageCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertPage", reflect.TypeOf((*HandlersMock)(nil).InsertPage), c)
	return &HandlersMockInsertPageCall{Call: call}
}

// HandlersMockInsertPageCall wrap *gomock.Call
type HandlersMockInsertPageCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c_2 *HandlersMockInsertPageCall) Return(arg0 error) *HandlersMockInsertPageCall {
	c_2.Call = c_2.Call.Return(arg0)
	return c_2
}

// Do rewrite *gomock.Call.Do
func (c_2 *HandlersMockInsertPageCall) Do(f func(*fiber.Ctx) error) *HandlersMockInsertPageCall {
	c_2.Call = c_2.Call.Do(f)
	return c_2
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c_2 *HandlersMockInsertPageCall) DoAndReturn(f func(*fiber.Ctx) error) *HandlersMockInsertPageCall {
	c_2.Call = c_2.Call.DoAndReturn(f)
	return c_2
}

// InstructionPage mocks base method.
func (m *HandlersMock) InstructionPage(c *fiber.Ctx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InstructionPage", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// InstructionPage indicates an expected call of InstructionPage.
func (mr *HandlersMockMockRecorder) InstructionPage(c any) *HandlersMockInstructionPageCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InstructionPage", reflect.TypeOf((*HandlersMock)(nil).InstructionPage), c)
	return &HandlersMockInstructionPageCall{Call: call}
}

// HandlersMockInstructionPageCall wrap *gomock.Call
type HandlersMockInstructionPageCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c_2 *HandlersMockInstructionPageCall) Return(arg0 error) *HandlersMockInstructionPageCall {
	c_2.Call = c_2.Call.Return(arg0)
	return c_2
}

// Do rewrite *gomock.Call.Do
func (c_2 *HandlersMockInstructionPageCall) Do(f func(*fiber.Ctx) error) *HandlersMockInstructionPageCall {
	c_2.Call = c_2.Call.Do(f)
	return c_2
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c_2 *HandlersMockInstructionPageCall) DoAndReturn(f func(*fiber.Ctx) error) *HandlersMockInstructionPageCall {
	c_2.Call = c_2.Call.DoAndReturn(f)
	return c_2
}
