// Code generated by MockGen. DO NOT EDIT.
// Source: ./interface.go
//
// Generated by this command:
//
//	mockgen -package dialog -mock_names IHandlers=HandlersMock -source ./interface.go -typed -destination interface.mock.gen.go
//

// Package dialog is a generated GoMock package.
package dialog

import (
	reflect "reflect"

	fiber "github.com/gofiber/fiber/v2"
	gomock "go.uber.org/mock/gomock"
)

// HandlersMock is a mock of IHandlers interface.
type HandlersMock struct {
	ctrl     *gomock.Controller
	recorder *HandlersMockMockRecorder
	isgomock struct{}
}

// HandlersMockMockRecorder is the mock recorder for HandlersMock.
type HandlersMockMockRecorder struct {
	mock *HandlersMock
}

// NewHandlersMock creates a new mock instance.
func NewHandlersMock(ctrl *gomock.Controller) *HandlersMock {
	mock := &HandlersMock{ctrl: ctrl}
	mock.recorder = &HandlersMockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *HandlersMock) EXPECT() *HandlersMockMockRecorder {
	return m.recorder
}

// DialogPage mocks base method.
func (m *HandlersMock) DialogPage(c *fiber.Ctx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DialogPage", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// DialogPage indicates an expected call of DialogPage.
func (mr *HandlersMockMockRecorder) DialogPage(c any) *HandlersMockDialogPageCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DialogPage", reflect.TypeOf((*HandlersMock)(nil).DialogPage), c)
	return &HandlersMockDialogPageCall{Call: call}
}

// HandlersMockDialogPageCall wrap *gomock.Call
type HandlersMockDialogPageCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c_2 *HandlersMockDialogPageCall) Return(arg0 error) *HandlersMockDialogPageCall {
	c_2.Call = c_2.Call.Return(arg0)
	return c_2
}

// Do rewrite *gomock.Call.Do
func (c_2 *HandlersMockDialogPageCall) Do(f func(*fiber.Ctx) error) *HandlersMockDialogPageCall {
	c_2.Call = c_2.Call.Do(f)
	return c_2
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c_2 *HandlersMockDialogPageCall) DoAndReturn(f func(*fiber.Ctx) error) *HandlersMockDialogPageCall {
	c_2.Call = c_2.Call.DoAndReturn(f)
	return c_2
}

// HistoryPage mocks base method.
func (m *HandlersMock) HistoryPage(c *fiber.Ctx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HistoryPage", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// HistoryPage indicates an expected call of HistoryPage.
func (mr *HandlersMockMockRecorder) HistoryPage(c any) *HandlersMockHistoryPageCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HistoryPage", reflect.TypeOf((*HandlersMock)(nil).HistoryPage), c)
	return &HandlersMockHistoryPageCall{Call: call}
}

// HandlersMockHistoryPageCall wrap *gomock.Call
type HandlersMockHistoryPageCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c_2 *HandlersMockHistoryPageCall) Return(arg0 error) *HandlersMockHistoryPageCall {
	c_2.Call = c_2.Call.Return(arg0)
	return c_2
}

// Do rewrite *gomock.Call.Do
func (c_2 *HandlersMockHistoryPageCall) Do(f func(*fiber.Ctx) error) *HandlersMockHistoryPageCall {
	c_2.Call = c_2.Call.Do(f)
	return c_2
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c_2 *HandlersMockHistoryPageCall) DoAndReturn(f func(*fiber.Ctx) error) *HandlersMockHistoryPageCall {
	c_2.Call = c_2.Call.DoAndReturn(f)
	return c_2
}
