// Code generated by MockGen. DO NOT EDIT.
// Source: ./interface.go
//
// Generated by this command:
//
//	mockgen -package user -mock_names IHandlers=HandlersMock -source ./interface.go -typed -destination interface.mock.gen.go
//

// Package user is a generated GoMock package.
package user

import (
	reflect "reflect"

	fiber "github.com/gofiber/fiber/v2"
	gomock "go.uber.org/mock/gomock"
)

// HandlersMock is a mock of IHandlers interface.
type HandlersMock struct {
	ctrl     *gomock.Controller
	recorder *HandlersMockMockRecorder
	isgomock struct{}
}

// HandlersMockMockRecorder is the mock recorder for HandlersMock.
type HandlersMockMockRecorder struct {
	mock *HandlersMock
}

// NewHandlersMock creates a new mock instance.
func NewHandlersMock(ctrl *gomock.Controller) *HandlersMock {
	mock := &HandlersMock{ctrl: ctrl}
	mock.recorder = &HandlersMockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *HandlersMock) EXPECT() *HandlersMockMockRecorder {
	return m.recorder
}

// GetInfo mocks base method.
func (m *HandlersMock) GetInfo(c *fiber.Ctx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInfo", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetInfo indicates an expected call of GetInfo.
func (mr *HandlersMockMockRecorder) GetInfo(c any) *HandlersMockGetInfoCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInfo", reflect.TypeOf((*HandlersMock)(nil).GetInfo), c)
	return &HandlersMockGetInfoCall{Call: call}
}

// HandlersMockGetInfoCall wrap *gomock.Call
type HandlersMockGetInfoCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c_2 *HandlersMockGetInfoCall) Return(arg0 error) *HandlersMockGetInfoCall {
	c_2.Call = c_2.Call.Return(arg0)
	return c_2
}

// Do rewrite *gomock.Call.Do
func (c_2 *HandlersMockGetInfoCall) Do(f func(*fiber.Ctx) error) *HandlersMockGetInfoCall {
	c_2.Call = c_2.Call.Do(f)
	return c_2
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c_2 *HandlersMockGetInfoCall) DoAndReturn(f func(*fiber.Ctx) error) *HandlersMockGetInfoCall {
	c_2.Call = c_2.Call.DoAndReturn(f)
	return c_2
}

// SettingsPage mocks base method.
func (m *HandlersMock) SettingsPage(c *fiber.Ctx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SettingsPage", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// SettingsPage indicates an expected call of SettingsPage.
func (mr *HandlersMockMockRecorder) SettingsPage(c any) *HandlersMockSettingsPageCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SettingsPage", reflect.TypeOf((*HandlersMock)(nil).SettingsPage), c)
	return &HandlersMockSettingsPageCall{Call: call}
}

// HandlersMockSettingsPageCall wrap *gomock.Call
type HandlersMockSettingsPageCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c_2 *HandlersMockSettingsPageCall) Return(arg0 error) *HandlersMockSettingsPageCall {
	c_2.Call = c_2.Call.Return(arg0)
	return c_2
}

// Do rewrite *gomock.Call.Do
func (c_2 *HandlersMockSettingsPageCall) Do(f func(*fiber.Ctx) error) *HandlersMockSettingsPageCall {
	c_2.Call = c_2.Call.Do(f)
	return c_2
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c_2 *HandlersMockSettingsPageCall) DoAndReturn(f func(*fiber.Ctx) error) *HandlersMockSettingsPageCall {
	c_2.Call = c_2.Call.DoAndReturn(f)
	return c_2
}

// Update mocks base method.
func (m *HandlersMock) Update(c *fiber.Ctx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *HandlersMockMockRecorder) Update(c any) *HandlersMockUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*HandlersMock)(nil).Update), c)
	return &HandlersMockUpdateCall{Call: call}
}

// HandlersMockUpdateCall wrap *gomock.Call
type HandlersMockUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c_2 *HandlersMockUpdateCall) Return(arg0 error) *HandlersMockUpdateCall {
	c_2.Call = c_2.Call.Return(arg0)
	return c_2
}

// Do rewrite *gomock.Call.Do
func (c_2 *HandlersMockUpdateCall) Do(f func(*fiber.Ctx) error) *HandlersMockUpdateCall {
	c_2.Call = c_2.Call.Do(f)
	return c_2
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c_2 *HandlersMockUpdateCall) DoAndReturn(f func(*fiber.Ctx) error) *HandlersMockUpdateCall {
	c_2.Call = c_2.Call.DoAndReturn(f)
	return c_2
}
